name: build_and_test

env:
  CONAN_UPLOAD: "${{ secrets.CONAN_UPLOAD }}"
  CONAN_LOGIN_USERNAME: "${{ secrets.CONAN_LOGIN_USERNAME }}"
  CONAN_PASSWORD: "${{ secrets.CONAN_PASSWORD }}"


on:
  push:
    branches:
      - "release/**"

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os:
          - windows-2019
          - ubuntu-20.04
          - macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install conan conan_package_tools pyelftools
            conan remote disable conancenter
      - name: Build and test
        run: echo "TODO"
