name: build_and_test

env:
  REFERENCE: "android-toolchain/r25c@conan-burrito/stable"

on:
  pull_request:
  push:
    branches:
      - "release/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os:
          - windows-2019
          - ubuntu-20.04
          - macos-12

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install conan pyelftools

      - name: Configure conan
        run: |
          conan --version
          conan profile detect
          conan remote disable conancenter
          conan remote add conan-burrito "${{ secrets.CONAN_UPLOAD }}"
          conan remote login conan-burrito "${{ secrets.CONAN_LOGIN_USERNAME }}" -p "${{ secrets.CONAN_PASSWORD }}"

      - name: Build toolchain
        run: conan create -pr:b default -pr:h ./.ci/profiles/armv7 --build-require --user=conan-burrito --channel=stable .

      - name: Run additional conan tests
        run: |
          cd test_package
          conan test -pr:b default -pr:h ../.ci/profiles/armv8 . ${{ env.REFERENCE }}
          conan test -pr:b default -pr:h ../.ci/profiles/x86 . ${{ env.REFERENCE }}
          conan test -pr:b default -pr:h ../.ci/profiles/x86_64 . ${{ env.REFERENCE }}

      - name: Run native check
        run: python3 toolchain_check/run-native-check.py

      - name: Run Android check
        run: python3 toolchain_check/run-android-check.py

      - name: Upload artefacts
        run: conan upload -r conan-burrito ${{ env.REFERENCE }}
