name: build_and_test

env:
  CONAN_REFERENCE: "android-toolchain/r21d"
  CONAN_USERNAME: "conan-burrito"
  CONAN_UPLOAD: "https://conan.yobasoft.de"
  CONAN_STABLE_BRANCH_PATTERN: "release/*"
  CONAN_LOGIN_USERNAME: "${{ secrets.CONAN_LOGIN_USERNAME }}"
  CONAN_PASSWORD: "${{ secrets.CONAN_PASSWORD }}"


on:
  push:
    branches:
      - "release/**"

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os:
          - ubuntu-20.04
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run:  pip install setuptools conan conan_package_tools pyelftools
      - name: Build and test
        run: python .ci/build.py
